# Generated by Django 2.2.2 on 2019-07-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0002_auto_20190725_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_entrada',
            old_name='created_date',
            new_name='fecha_ingreso',
        ),
        migrations.RenameField(
            model_name='stock_salida',
            old_name='created_date',
            new_name='fecha_vendido',
        ),
        migrations.RemoveField(
            model_name='stock_entrada',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='stock_salida',
            name='published_date',
        ),
    ]
