# Generated by Django 2.2.2 on 2019-07-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0003_auto_20190725_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='proovedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100, unique=True)),
                ('CUIL_empresa', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=100)),
            ],
        ),
        migrations.DeleteModel(
            name='proovedores',
        ),
    ]
