# Generated by Django 2.2.2 on 2019-07-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0004_auto_20190725_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='ISBC',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='producto',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='proovedor',
            name='CUIL_empresa',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='proovedor',
            name='direccion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='proovedor',
            name='empresa',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='stock_entrada',
            name='proovedor',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='stock_salida',
            name='producto_salida',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
